@startuml caso_uso
left to right direction
skinparam packageStyle rectangle

title Diagrama de Casos de Uso - Sistema de Gestión de Tareas

actor Usuario as U
actor Administrador as A

rectangle "Sistema de Gestión de Tareas" {
  U -- (Crear Tarea)
  U -- (Asignar Tarea)
  U -- (Ver Tareas)
  U -- (Actualizar Tarea)
  U -- (Eliminar Tarea)

  U -- (Detectar Ciclos)
  U -- (Orden Topológico)
  U -- (Reconectar MongoDB)

  A -- (Insertar Empleado)
  A -- (Eliminar Empleado)
}

note right of U
Usuarios (empleados) interactúan con
la UI para crear/visualizar tareas.
end note

note left of A
Administrador gestiona datos y
operaciones de mantenimiento.
end note

@enduml